CREATE DATABASE IF NOT EXISTS user_management;
USE user_management;
Database changed
CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
phone_number VARCHAR(10) NOT NULL,
pan_number VARCHAR(10) NOT NULL
);
